version: '3'
services:
  server:
    image: node:12.18.4
    working_dir: /code
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=onyourmind
      - PGHOST=db
      - PGPASSWORD=onyourmindpassword
      - PGDATABASE=thoughts
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./server
        target: /code
    command: bash -c "npm install && npm start"
  db:
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./server/dbthoughts:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_DB=thoughts
      - POSTGRES_USER=onyourmind
      - POSTGRES_PASSWORD=onyourmindpassword
volumes:
  dbdata: